### ISSUE TITLE
Publish docs

### ISSUE THREAD

**Issue by ali-ramadhan** [glwagner/SeawaterPolynomials.jl#13]
Can't seem to do it myself as I don't have access to the repo settings. But https://glwagner.github.io/SeawaterPolynomials.jl/stable/ doesn't seem to work.

Would be good to get the page of docstrings up as we need to link to them from the Oceananigans.jl docs.

**Comment by navidcy** [comment]
@glwagner I can help with that if you give me repo ownership access.
