### ISSUE TITLE
Equation of State for TEOS10: Depth vs Height

### ISSUE THREAD

**Issue by sandreza** [glwagner/SeawaterPolynomials.jl#19]
It seems that the Roquet et. al paper uses a different sign convention in the following definition

<img width="525" alt="Screen Shot 2022-05-05 at 11 41 40 PM" src="https://user-images.githubusercontent.com/22668662/167149753-a9ee2db0-ade4-420f-9a1a-c4e73ba795d3.png">

as compared to what is in the package: 

https://github.com/CliMA/SeawaterPolynomials.jl/blob/5f278c85e849d402de9d45f20fa3f227e0b8e6fc/src/TEOS10.jl#L68

This can lead to subtle sign errors that propagate to other code bases

**Comment by glwagner** [comment]
I think we should add a minus sign to 

https://github.com/CliMA/SeawaterPolynomials.jl/blob/5f278c85e849d402de9d45f20fa3f227e0b8e6fc/src/TEOS10.jl#L68

we also have to update a test.

**Comment by glwagner** [comment]
Thanks a lot @sandreza for finding this!

**Comment by sandreza** [comment]
closed via #20
