### ISSUE TITLE
Use `a` and `b` for thermal and haline sensitivity to distinguish them with thermal expansion and haline contraction

### ISSUE THREAD

**Issue by xkykai** [glwagner/SeawaterPolynomials.jl#30]
In the docs thermal sensitivity and expansion are expressed as $\alpha$, and haline sensitivity and contraction are expressed as $\beta$. However, the sensitivity differs with expansion/contraction by a factor of density $\rho_\mathrm{ref}$.

https://github.com/CliMA/SeawaterPolynomials.jl/blob/08b3532dfa9d938d12750050a614e4636949d1be/src/SeawaterPolynomials.jl#L109
https://github.com/CliMA/SeawaterPolynomials.jl/blob/08b3532dfa9d938d12750050a614e4636949d1be/src/SeawaterPolynomials.jl#L132

https://github.com/CliMA/SeawaterPolynomials.jl/blob/08b3532dfa9d938d12750050a614e4636949d1be/src/SeawaterPolynomials.jl#L11
https://github.com/CliMA/SeawaterPolynomials.jl/blob/08b3532dfa9d938d12750050a614e4636949d1be/src/SeawaterPolynomials.jl#L33

Not sure if anyone else might be confused by them at first glance but I was certainly confused by them for quite some time.

In Roquet et al. 2015 they distinguish these terms by using $a$ and $b$ for the sensitivities, if we agree that following their convention might be helpful and there is a need to distinguish them in the docs.

**Comment by glwagner** [comment]
Yes, we should definitely change the docs! I think we forgot to change the docs when we introduced the new functions `thermal_sensitivity`, etc
