### ISSUE TITLE
Error in docstring for `:Linear` coefficient set

### ISSUE THREAD

**Issue by jbisits** [glwagner/SeawaterPolynomials.jl#36]
I think that the coefficients (`R₁₀₀`, `R₀₁₀`) in the docstring for the `:Linear` coefficient set have been switched around

https://github.com/CliMA/SeawaterPolynomials.jl/blob/54499e33783f78f117f12abda7bce2cfe056c832/src/SecondOrderSeawaterPolynomials.jl#L96

In the rest of the coefficient sets `R₁₀₀` corresponds to salinity and `R₀₁₀` corresponds to temperature

https://github.com/CliMA/SeawaterPolynomials.jl/blob/54499e33783f78f117f12abda7bce2cfe056c832/src/SecondOrderSeawaterPolynomials.jl#L98-L112

This only occurs in this docstring, `RoquetEquationOfState(:Linear)` sets everything correctly 

https://github.com/CliMA/SeawaterPolynomials.jl/blob/54499e33783f78f117f12abda7bce2cfe056c832/src/SecondOrderSeawaterPolynomials.jl#L161-L163

**Comment by glwagner** [comment]
nice catch
